### ISSUE TITLE
Charts are not displaying 

### ISSUE THREAD

**Issue by samuelgfeller** [sashatrubetskoy/20colors#5]
https://sashamaps.net/docs/resources/20-colors/

![image](https://user-images.githubusercontent.com/31797204/102757227-49981080-4371-11eb-9519-f24aaf7de760.png)

**Comment by a-trubetskoy** [comment]
What browser are you on? Everything works for me on Chrome and Safari

**Comment by samuelgfeller** [comment]
I was on the new edge and tested it in a private window as well. 
But now it displays correctly somehow.
Anyway I close the issue, thanks for responding ( and the site :) ).
